FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Expose port
EXPOSE 422

# Start development server
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4223", "--poll=500", "--hmr"]
